In [1]:
import pandas as pd

In [2]:
drivers = pd.read_csv("../data/drivers.csv")

drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [3]:
import requests

url = "https://api.jolpi.ca/ergast/f1/2025/drivers.json"

respuesta = requests.get(url)

print(respuesta.status_code)

200

In [4]:
datos = respuesta.json()

print(datos.keys())

dict_keys(['MRData'])

In [5]:
drivers = datos["MRData"]["DriverTable"]["Drivers"]

len(drivers)

30

In [6]:
import pandas as pd

drivers_df = pd.DataFrame(drivers)

drivers_df.head()

,driverId,permanentNumber,code,url,givenName,familyName,dateOfBirth,nationality
0,albon,23,ALB,http://en.wikipedia.org/wiki/Alexander_Albon,Alexander,Albon,1996-03-23,Thai
1,alonso,14,ALO,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando,Alonso,1981-07-29,Spanish
2,antonelli,12,ANT,https://en.wikipedia.org/wiki/Andrea_Kimi_Anto...,Andrea Kimi,Antonelli,2006-08-25,Italian
3,paul_aron,NaN,NaN,NaN,Paul,Aron,NaN,NaN
4,bearman,87,BEA,http://en.wikipedia.org/wiki/Oliver_Bearman,Oliver,Bearman,2005-05-08,British

In [11]:
drivers = pd.read_csv("../data/drivers.csv")
races = pd.read_csv("../data/races.csv")
results = pd.read_csv("../data/results.csv")
driver_standings = pd.read_csv("../data/driver_standings.csv")

In [12]:
drivers.info()
drivers.head()

<class 'pandas.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     861 non-null    int64
 1   driverRef    861 non-null    str
 2   number       861 non-null    str
 3   code         861 non-null    str
 4   forename     861 non-null    str
 5   surname      861 non-null    str
 6   dob          861 non-null    str
 7   nationality  861 non-null    str
 8   url          861 non-null    str
dtypes: int64(1), str(8)
memory usage: 60.7 KB

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [13]:
races.info()
races.head()

<class 'pandas.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   str
 5   date         1125 non-null   str
 6   time         1125 non-null   str
 7   url          1125 non-null   str
 8   fp1_date     1125 non-null   str
 9   fp1_time     1125 non-null   str
 10  fp2_date     1125 non-null   str
 11  fp2_time     1125 non-null   str
 12  fp3_date     1125 non-null   str
 13  fp3_time     1125 non-null   str
 14  quali_date   1125 non-null   str
 15  quali_time   1125 non-null   str
 16  sprint_date  1125 non-null   str
 17  sprint_time  1125 non-null   str
dtypes: int64(4), str(14)
memory usage: 158.3 KB

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [14]:
results.info()
results.head()

<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  str
 5   grid             26759 non-null  int64
 6   position         26759 non-null  str
 7   positionText     26759 non-null  str
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  str
 12  milliseconds     26759 non-null  str
 13  fastestLap       26759 non-null  str
 14  rank             26759 non-null  str
 15  fastestLapTime   26759 non-null  str
 16  fastestLapSpeed  26759 non-null  str
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [15]:
driver_standings.info()
driver_standings.head()

<class 'pandas.DataFrame'>
RangeIndex: 34863 entries, 0 to 34862
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driverStandingsId  34863 non-null  int64
 1   raceId             34863 non-null  int64
 2   driverId           34863 non-null  int64
 3   points             34863 non-null  float64
 4   position           34863 non-null  int64
 5   positionText       34863 non-null  str
 6   wins               34863 non-null  int64
dtypes: float64(1), int64(5), str(1)
memory usage: 1.9 MB

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [16]:
drivers[drivers["nationality"] == "Argentine"]

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
59,60,mazzacane,\N,\N,Gastón,Mazzacane,1975-05-08,Argentine,http://en.wikipedia.org/wiki/Gast%C3%B3n_Mazza...
73,74,tuero,\N,\N,Esteban,Tuero,1978-04-22,Argentine,http://en.wikipedia.org/wiki/Esteban_Tuero
81,82,fontana,\N,\N,Norberto,Fontana,1975-01-20,Argentine,http://en.wikipedia.org/wiki/Norberto_Fontana
164,165,larrauri,\N,\N,Oscar,Larrauri,1954-08-19,Argentine,http://en.wikipedia.org/wiki/Oscar_Larrauri
198,199,reutemann,\N,\N,Carlos,Reutemann,1942-04-12,Argentine,http://en.wikipedia.org/wiki/Carlos_Reutemann
214,215,guerra,\N,\N,Miguel Ángel,Guerra,1953-08-31,Argentine,http://en.wikipedia.org/wiki/Miguel_Angel_Guerra
216,217,zunino,\N,\N,Ricardo,Zunino,1949-04-13,Argentine,http://en.wikipedia.org/wiki/Ricardo_Zunino
438,439,estefano,\N,\N,Nasif,Estéfano,1932-11-18,Argentine,http://en.wikipedia.org/wiki/Nasif_Est%C3%A9fano
485,485,bordeu,\N,\N,Juan Manuel,Bordeu,1934-01-28,Argentine,http://en.wikipedia.org/wiki/Juan_Manuel_Bordeu
496,496,menditeguy,\N,\N,Carlos,Menditeguy,1914-08-10,Argentine,http://en.wikipedia.org/wiki/Carlos_Menditeguy
497,497,larreta,\N,\N,Alberto Rodriguez,Larreta,1934-01-14,Argentine,http://en.wikipedia.org/wiki/Alberto_Rodriguez...
498,498,gonzalez,\N,\N,José Froilán,González,1922-10-05,Argentine,http://en.wikipedia.org/wiki/Jos%C3%A9_Froil%C...
499,499,bonomi,\N,\N,Roberto,Bonomi,1919-09-30,Argentine,http://en.wikipedia.org/wiki/Roberto_Bonomi
579,579,fangio,\N,\N,Juan,Fangio,1911-06-24,Argentine,http://en.wikipedia.org/wiki/Juan_Manuel_Fangio
643,643,mieres,\N,\N,Roberto,Mieres,1924-12-03,Argentine,http://en.wikipedia.org/wiki/Roberto_Mieres
645,645,bucci,\N,\N,Clemar,Bucci,1920-09-04,Argentine,http://en.wikipedia.org/wiki/Clemar_Bucci
646,646,iglesias,\N,\N,Jesús,Iglesias,1922-02-22,Argentine,http://en.wikipedia.org/wiki/Jes%C3%BAs_Iglesias
649,649,birger,\N,\N,Pablo,Birger,1924-01-07,Argentine,http://en.wikipedia.org/wiki/Pablo_Birger
670,670,marimon,\N,\N,Onofre,Marimón,1923-12-19,Argentine,http://en.wikipedia.org/wiki/Onofre_Marim%C3%B3n
672,672,daponte,\N,\N,Jorge,Daponte,1923-06-05,Argentine,http://en.wikipedia.org/wiki/Jorge_Daponte
695,695,galvez,\N,\N,Oscar,Gálvez,1913-08-17,Argentine,http://en.wikipedia.org/wiki/%C3%93scar_Alfred...
698,698,cruz,\N,\N,Adolfo,Cruz,1923-06-28,Argentine,http://en.wikipedia.org/wiki/Adolfo_Schewelm_Cruz
761,761,crespo,\N,\N,Alberto,Crespo,1920-01-16,Argentine,http://en.wikipedia.org/wiki/Alberto_Crespo
792,792,pian,\N,\N,Alfredo,Pián,1912-10-21,Argentine,http://en.wikipedia.org/wiki/Alfredo_Pi%C3%A0n

In [17]:
drivers["nationality"].unique()

<StringArray>
[          'British',            'German',           'Spanish',
           'Finnish',          'Japanese',            'French',
            'Polish',         'Brazilian',           'Italian',
        'Australian',          'Austrian',          'American',
             'Dutch',         'Colombian',        'Portuguese',
          'Canadian',            'Indian',         'Hungarian',
             'Irish',            'Danish',         'Argentine',
             'Czech',         'Malaysian',             'Swiss',
           'Belgian',        'Monegasque',           'Swedish',
        'Venezuelan',     'New Zealander',           'Chilean',
           'Mexican',     'South African',   'Liechtensteiner',
         'Rhodesian',  'American-Italian',         'Uruguayan',
 'Argentine-Italian',              'Thai',       'East German',
           'Russian',        'Indonesian',           'Chinese',
      'Argentinian ']
Length: 43, dtype: str

In [19]:
drivers.columns
races.columns
results.columns
driver_standings.columns

Index(['driverStandingsId', 'raceId', 'driverId', 'points', 'position',
       'positionText', 'wins'],
      dtype='str')